# Use root/example as user/password credentials
version: '3.1'

services:

  api:
    build:
      context: ./api/
    image: clip.api:latest
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.27
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: clip!
    ports:
      - 3306:3306